name = "Pack"
uuid = "920fdb52-f93c-47e6-97a3-e69691e03beb"
authors = ["Thomas Staudt <tscode@posteo.net>"]
version = "0.1.0"

[weakdeps]
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extensions]
TranscodingStreamsExt = ["TranscodingStreams"]
DatesExt = ["Dates"]

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
